export { default as Header } from "./Header";
export { default as Body } from "./Body";
export { default as Product } from "./Product";
export { default as Footer } from "./Footer";
export { default as Checkout } from "./checkout";
export { default as Subtotal } from "./Subtotal";
export { default as CheckoutProduct } from "./checkoutProduct";
export { default as Form } from "./Form";
export { default as Payment } from "./Payment";
